{
  if (throwException) {
    throw new Error("cause invocation failure");
  }
}
