{
  LOG.debug(exception.getMessage(),exception);
  try {
    debug.startSection("Exception");
    debug.appendException(exception);
    debug.endSection();
  }
 catch (  final RuntimeException e) {
    debug.appendln("NOTE - an exception occurred while dumping an exception!");
    debug.appendException(e);
  }
  message=exception.getMessage();
}
